# Generated by Django 5.0.4 on 2024-04-30 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=50)),
                ('question_txt', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='categorys.categorys')),
            ],
            options={
                'ordering': ['question_id'],
            },
        ),
    ]
