# Generated by Django 5.0.4 on 2024-04-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_txt', models.CharField(max_length=100)),
            ],
        ),
    ]
