# Generated by Django 5.0.4 on 2024-04-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic_quest',
            fields=[
                ('statistic_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('incorrect_answers', models.IntegerField()),
                ('percentage_correct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_all_questions', models.IntegerField()),
                ('total_all_correct_answers', models.IntegerField()),
                ('total_all_incorrect_answers', models.IntegerField()),
            ],
        ),
    ]
